<?php

	$databaseHost = 'localhost';
	$databaseName = 'data';
	$databaseUsername = 'root';
	$databasePassword = '';
	$mysqli = mysqli_connect($databaseHost, $databaseUsername, $databasePassword, $databaseName);

	

 
    $id = $_GET['id'];
    $stat = $_GET['stat'];

    if  ($stat =="S") {
            $usbar = $_GET['username'];
            $pasbar = $_GET['password'];
            $sql3 = mysqli_query($mysqli, "UPDATE users SET username='$usbar',password='$pasbar'  WHERE id=$id");
            $result3 = mysqli_query($mysqli, $sql3);
            $sql4 = "SELECT username,password,id from users where id=$id";
            $result4 = mysqli_query($mysqli, $sql4);
            $row3 = mysqli_fetch_array($result4);
            header('Refresh:0.00001;  admin'."?".'username='.$usbar.'&password='.$pasbar);
            ?><script>alert('Username dan Password berhasil di simpan!');</script><?php
            


     



}else{
    $sql4 = "SELECT username,password,id from users where id=$id";
    $result4 = mysqli_query($mysqli, $sql4);
    
    $row3 = mysqli_fetch_array($result4);

}   



?>
<head>  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<style>   
body {  

  font-family: Calibri, Helvetica, sans-serif;  
  background-color: white;  
}  
button {   
       background-color: #343a40;   
       width: 100%;  
        color: white;   
        padding: 15px;   
        margin: 10px 0px;   
        border: none;   
        cursor: pointer;   
         }   
 form {   
        border: 3px solid #E9ECEF;
        background-color: #E9ECEF;    
    }   
 input[type=text], input[type=password] {   
        width: 100%;   
        margin: 8px 0;  
        padding: 12px 20px;   
        display: inline-block;   
        border: 2px solid #E9ECEF;   
        box-sizing: border-box;   
    }  
 button:hover {   
        opacity: 0.7;   
    }   
     
 .container {   

        padding: 25px;   
         
    }   

</style>   
</head>    

	
    <center> <h1> Edit User  </h1> </center>   
    <form >  
        <div class="container">   
        <form method="get" action="<?php echo $this->url(array('controller'=>'index', 'action'=>'edito')); ?>">
            <form>
            <label>Username  </label>   
            <input type="text" value="<?php echo $_GET=$row3['username']?>" disabled>  
            <label>Password  </label>   
            <input type="text" value="<?php echo $_GET=$row3['password']?>" disabled>  
            <label>Username Baru  </label>   
            <input type="text" placeholder="Enter New Username" name="username" id="nu" required>  
            <label>Password Baru </label>   
            <input type="password" placeholder="Enter New Password" name="password" id="np" required> 
            <input type="hidden"  name="id" id="nid" value="<?php echo $_GET=$row3['id']?>" required>
            <button type="submit" name= "stat"value="S" >Simpan</button> 
         </form>

		</form>
        </div>   
    </form>  

    
    
