

<head>  
<meta name="viewport" content="width=device-width, initial-scale=1">  
<title> Login Page </title>  
<style>   
body {  

  font-family: Calibri, Helvetica, sans-serif;  
  background-color: white;  
}  
button {   
       background-color: #343a40;   
       width: 100%;  
        color: white;   
        padding: 15px;   
        margin: 10px 0px;   
        border: none;   
        cursor: pointer;   
         }   
 form {   
        border: 3px solid #E9ECEF;
        background-color: #E9ECEF;    
    }   
 input[type=text], input[type=password] {   
        width: 100%;   
        margin: 8px 0;  
        padding: 12px 20px;   
        display: inline-block;   
        border: 2px solid #E9ECEF;   
        box-sizing: border-box;   
    }  
 button:hover {   
        opacity: 0.7;   
    }   
     
 .container {   

        padding: 25px;   
         
    }   

</style>   
</head>    

	
    <center> <h1> Admin Login </h1> </center>   
    <form method="get" action="<?php echo $this->url(array('controller'=>'index', 'action'=>'admin')); ?>">  
        <div class="container">   
        <form >
            <label>Username  </label>   
            <input type="text" placeholder="Enter Username" name="username" id="username" required>  
            <label>Password  </label>   
            <input type="password" placeholder="Enter Password" name="password" id="password" required>  
            <button type="submit" >Login</button>   
		</form>
        </div>   
    </form>  
    
    
